package hub

import (
	"encoding/json"
	"regexp"
	"strings"

	"github.com/howlerops/oculus/daemon/fsaccess"
	"github.com/howlerops/oculus/daemon/protocol"
)

// Repository metadata is off limits to agents, and this is a SECURITY rule rather than a tidiness
// one: a write into .git turns into code execution later, performed by us.
//
// The chain, end to end:
//
//  1. An agent writes .git/hooks/pre-commit inside its own worktree. The path is inside the
//     worktree, so every prefix-based check passes, and the approval card shows what reads as an
//     ordinary file write.
//  2. The user picks that variant and hits Finish.
//  3. The DAEMON runs `git add -A && git commit` (worktree/finish.go), or `git merge` on the main
//     checkout, or `git push`. None of them pass --no-verify.
//  4. Git executes the hook as the owner.
//
// The relay makes step 1 reachable from a phone anywhere, which is precisely the standard that got
// encrypted PTY sessions parked: a capability that ends in arbitrary code execution, reachable
// remotely, cannot be handed over on a card that doesn't look like it. The only thing separating
// this from a shell is the delay — and the delay makes it harder to notice, not safer.
//
// Refused rather than merely surfaced, because the disclosure people would rely on doesn't hold.
// `core.hooksPath` can point anywhere, so the file need not be called .git/hooks/anything: an agent
// can write .oculus-tools/pre-commit — an unremarkable-looking path — and redirect hooks to it with
// a `git config` call that reads as routine housekeeping.
//
// Legitimate hooks are deliberately left working. The alternative fix (--no-verify on every
// daemon-initiated git operation) closes the same hole, but it silently stops a repo's real
// pre-commit hooks — formatters, linters — from running on agent commits, which changes what lands.
// Blocking the write keeps honest repos behaving exactly as they did.
type approvalGuard struct {
	// reason is empty when the request is allowed to proceed to the user.
	reason string
}

// hooksPathRe matches an attempt to redirect git's hook directory. Deliberately broad about the
// surrounding command: this appears as `git config core.hooksPath X`, `git -C dir config --local
// core.hooksPath X`, and inside compound shell lines, and the option is case-insensitive to git.
var hooksPathRe = regexp.MustCompile(`(?i)\bcore\.hookspath\b`)

// guardApproval judges a request BEFORE it is auto-allowed or shown to the user. A non-empty reason
// means deny outright: these are not decisions a person should be asked to make on a one-line card,
// because the consequence is invisible at the moment of asking and arrives later, from us.
func guardApproval(ar protocol.ApprovalRequest) approvalGuard {
	tool := strings.ToLower(strings.TrimSpace(ar.Tool))
	tool = strings.TrimPrefix(tool, "[sub-agent] ")
	// An MCP tool arrives qualified as `mcp:<server>:<tool>` so a rule can name one server's tool
	// without colliding with a native one. The guard wants the bare name: a shell exposed by an MCP
	// server is still a shell, and `mcp:shelly:bash` must match isShellTool exactly as `bash` does.
	if rest, ok := strings.CutPrefix(tool, "mcp:"); ok {
		if _, bare, found := strings.Cut(rest, ":"); found {
			tool = bare
		}
	}

	// Any tool that names a path: refuse the ones that land in repository metadata. Checked for
	// EVERY tool rather than a write allowlist, because a tool we haven't seen is exactly the one
	// whose behaviour we can't predict — and a harness that invents `SaveFile` should not get a pass
	// that `write` doesn't.
	for _, cand := range approvalPaths(ar) {
		if meta := fsaccess.VCSMetadataComponent(cand); meta != "" {
			return approvalGuard{reason: "writes into " + meta + " are refused — a hook placed there " +
				"would be executed by Iron Rain's own git commit/merge when you finish this session"}
		}
	}

	// Redirecting hooksPath achieves the same thing without ever naming .git, so the path rule alone
	// is not enough. Only shell-ish tools can run it.
	//
	// Scanned across Detail AND the raw arguments for the same reason the path check is: Detail is a
	// human-readable summary each harness writes however it likes, and an MCP server's Detail is
	// generated by US ("bash (via the shelly MCP server)") — it cannot contain the command, which
	// arrives only in the arguments. Checking Detail alone would leave every MCP shell unguarded.
	if isShellTool(tool) && hooksPathRe.MatchString(ar.Detail+" "+string(ar.Input)) {
		return approvalGuard{reason: "changing core.hooksPath is refused — it redirects git's hooks " +
			"to a directory the agent controls, which Iron Rain's own git commit/merge would then execute"}
	}
	return approvalGuard{}
}

// isShellTool reports whether a tool executes a command line, so the hooksPath rule is applied to
// the things that could actually run it rather than to every Detail string in the system.
func isShellTool(tool string) bool {
	switch tool {
	case "bash", "shell", "run", "execute", "terminal", "command", "sh", "zsh":
		return true
	}
	return false
}

// approvalPaths returns the filesystem paths a request refers to.
//
// All THREE sources are checked, and Input is the one that matters most: it is the tool's raw
// arguments, i.e. the thing the harness will actually act on. Detail is a human-readable summary
// whose content is up to each harness, and Patterns is opencode's permission scoping. A guard built
// on Detail alone passes its unit tests and then fails in production, because the test feeds Detail
// the path while the real harness puts it in Input — which is exactly what happened here: a live
// attempt to write .git/hooks/pre-commit sailed through to the approval card.
func approvalPaths(ar protocol.ApprovalRequest) []string {
	out := make([]string, 0, len(ar.Patterns)+4)
	if d := strings.TrimSpace(ar.Detail); d != "" && !strings.Contains(d, "\n") {
		// A Detail that is a whole shell command is not a path; taking its first token would judge
		// `git` rather than anything real. Only treat it as a path when it looks like one.
		if looksLikePath(d) {
			out = append(out, d)
		}
	}
	out = append(out, ar.Patterns...)
	out = append(out, inputPaths(ar.Input)...)
	return out
}

// pathKeys are the argument names harnesses use for "the file this operates on". Kept as a list
// rather than "any string that looks like a path" so a prompt or a commit message that happens to
// mention .git does not refuse the operation.
var pathKeys = []string{
	"file_path", "filePath", "path", "notebook_path", "notebookPath",
	"target_file", "targetFile", "old_path", "new_path", "destination", "dest", "source", "src",
}

// inputPaths pulls the filesystem targets out of a tool's raw arguments, including one level of
// nesting (harnesses wrap edits in an "edits"/"files" array) so a batch edit cannot smuggle a path
// past a top-level-only scan.
func inputPaths(raw json.RawMessage) []string {
	if len(raw) == 0 {
		return nil
	}
	var obj map[string]any
	if json.Unmarshal(raw, &obj) != nil {
		return nil
	}
	var out []string
	collect := func(m map[string]any) {
		for _, k := range pathKeys {
			if s, ok := m[k].(string); ok && strings.TrimSpace(s) != "" {
				out = append(out, s)
			}
		}
	}
	collect(obj)
	for _, v := range obj {
		nested, ok := v.([]any)
		if !ok {
			continue
		}
		for _, item := range nested {
			if m, ok := item.(map[string]any); ok {
				collect(m)
			}
		}
	}
	return out
}

// looksLikePath is intentionally conservative: it is used to decide whether to APPLY a restriction,
// so a false negative merely means the Patterns check carries the weight, while a false positive
// would refuse an innocuous command for containing a slash.
func looksLikePath(s string) bool {
	if strings.ContainsAny(s, " \t") {
		return false // a command line, not a path
	}
	return strings.Contains(s, "/")
}
